version: '3.9'

networks:
  mfc-networks:

services:

  # nginx
  nginx-service:
    image: nginx:alpine
    container_name: nginx-container
    working_dir: /var/www/project
    ports:
      - "8001:80"
    volumes:
      - ./../backend:/var/www/project
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - mfc-networks

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./../backend:/var/www/project
    networks:
      - mfc-networks

    # mysql
  mysql-service:
    image: mysql:8
    platform: linux/x86_64
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mfc-networks

    # node
#  node-service:
#    image: node:latest
#    container_name: node-container
#    working_dir: /var/www/project
#    volumes:
#      - ./app:/var/www/project
#    networks:
#      - mfc-networks
